apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-triton
  namespace: triton
spec:
  type: {{ .Values.service.type }}
  selector:
    app: triton-inference-server
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePorts.http }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: 8001
      nodePort: {{ .Values.service.nodePorts.grpc }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: 8002
      nodePort: {{ .Values.service.nodePorts.metrics }}