replicaCount: 1

image:
  repository: ghcr.io/krishpn/cicdtest/triton-inference-server
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

runtimeClassName: nvidia

resources:
  limits:
    nvidia.com/gpu: 1
    memory: 16Gi
    cpu: "8"
  requests:
    nvidia.com/gpu: 1
    memory: 8Gi
    cpu: "4"

shmSize: 4Gi

triton:
  modelRepositoryPath: "/opt/model_repository"
  modelControlMode: "explicit"

hostPath:
  enabled: true
  path: "/home/krishna/Documents/personal/practice/triton/nkepsX/model_repository"

service:
  type: NodePort
  httpPort: 8000
  grpcPort: 8001
  metricsPort: 8002
  nodePorts:
    http: 30800
    grpc: 30801
    metrics: 30802