apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triton-inference-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: 'https://github.com/krishpn/cicdtest.git'
    targetRevision: HEAD
    path: helm/triton-inference-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: triton
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
